import Foundation

// MARK: - For You Feed Response DTO

/// 对应后端 `ForYouFeedResponse`（snake_case → JSONDecoder convertFromSnakeCase）
struct ForYouFeedResponseDTO: Decodable {
    let items: [FeedCardDTO]?
    let nextCursor: String?
    let hasMore: Bool?
    let matchedLanguage: String?
    let fallbackReason: String?
}

/// 对应后端 `FeedCardDto`
struct FeedCardDTO: Decodable {
    let seriesId: Int64
    let previewEpisodeId: Int64?
    let localizedTitle: String?
    let localizedSynopsis: String?
    let coverUrl: String?
    let tags: [String]?
    let playAsset: PlayAssetDTO?
    let monetization: MonetizationDTO?
    let contentLanguage: String?
    let matchedLanguage: String?
    let countryCode: String?
    let fallbackReason: String?
    let recommendationTraceId: String?
}

/// 对应后端 `monetization` Map
struct MonetizationDTO: Decodable {
    let isFree: Bool?
    let vipRequired: Bool?
    let unlockCoinCost: Decimal?
}

/// 对应后端 `play_asset` Map（简版：仅含 master URL / fallback / qualities 摘要）
struct PlayAssetDTO: Decodable {
    let hlsMasterUrl: String?
    let mp4FallbackUrl: String?
    let qualities: [QualityDTO]?
    let subtitles: [SubtitleDTO]?
}

struct QualityDTO: Decodable {
    let quality: String?
    let url: String?
    let width: Int?
    let height: Int?
    let bitrateKbps: Int?
    let codec: String?
    let fileSize: Int64?
    let vipRequired: Bool?
}

struct SubtitleDTO: Decodable {
    let lang: String?
    let url: String?
    let type: String?
    let isDefault: Bool?
    let isAutoGenerated: Bool?
}
